name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 每次推送到 main 分支时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 允许写入 GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=
            type=ref,event=branch,enable=${{ github.ref_name != 'main' }} # 只为非 main 分支添加 branch 标签
            type=raw,value=dev,enable=${{ github.ref_name == 'main' }} # 为 main 分支添加 dev 标签

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}